apiVersion: apps/v1
kind: Deployment
metadata:
  name: inspector
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: "inspector"
    app.kubernetes.io/version: "{{ .Values.appVersion }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: inspector
  template:
    metadata:
      labels:
        app: inspector
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: inspector-sa
      containers:
        - name: inspector
          image: "{{ .Values.image }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          envFrom:
            - configMapRef:
                name: inspector-config
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          livenessProbe:
            httpGet:
              path: /ping
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ping
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 5
