apiVersion: apps/v1
kind: Deployment
metadata:
  name: receiver
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: "receiver"
    app.kubernetes.io/version: "{{ .Values.appVersion }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: receiver
  template:
    metadata:
      labels:
        app: receiver
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: receiver-sa
      containers:
        - name: receiver
          image: "{{ .Values.image }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          envFrom:
            - configMapRef:
                name: receiver-config
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault