apiVersion: v1
kind: Namespace
metadata:
  name: publisher
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: publisher-sa
  namespace: publisher
  annotations:
    azure.workload.identity/client-id: UMI_CLIENT_ID
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: publisher-config
  namespace: publisher
data:
  SERVICEBUS_NAMESPACE: "sb-apps-cust-dev.servicebus.windows.net"
  SERVICEBUS_TOPIC_NAME: "events"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher
  namespace: publisher
spec:
  replicas: 2
  selector:
    matchLabels:
      app: publisher
  template:
    metadata:
      labels:
        app: publisher
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: publisher-sa
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: publisher
          image: IMAGE_NAME
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: publisher-config

---
apiVersion: v1
kind: Service
metadata:
  name: publisher
  namespace: publisher
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    app: publisher
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: publisher
