apis:
  - name: echo
    properties:
      apiRevision: 1
      serviceUrl: "https://login.microsoftonline.com/16850073-4977-4869-9163-08e8d38eac81/oauth2"
    diagnostics:
      - name: applicationinsights
        properties:
          loggerId: "/subscriptions/315e574e-7153-4853-8cfe-fa416bb08a23/resourceGroups/z-rg-aks-dev/providers/Microsoft.ApiManagement/service/apim-custom-2xkl/loggers/appinsights-logger"