apis:
  - name: echo
    properties:
      apiRevision: 1
      serviceUrl: "http://SERVICE_IP"
    diagnostics:
      - name: applicationinsights
        properties:
          loggerId: "/subscriptions/42cc25b1-5f27-40a1-a857-9668d4e6e278/resourceGroups/z-rg-aks-dev/providers/Microsoft.ApiManagement/service/apim-custom-2xkl/loggers/appinsights-logger"