apis:
  - name: echo
    properties:
      apiRevision: 1
      serviceUrl: "10.1.1.33"
    diagnostics:
      - name: applicationinsights
        properties:
          loggerId: "/subscriptions/315e574e-7153-4853-8cfe-fa416bb08a23/resourceGroups/z-rg-aks-dev/providers/Microsoft.ApiManagement/service/apim-custom-2xkl/loggers/appinsights-logger"