apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/version: {{ .Values.appVersion }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: chat-sa
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      containers:
        - name: chat
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          envFrom:
            - configMapRef:
                name: chat-config
