openapi: 3.0.1
info:
  title: publisher
  description: ''
  version: '1.0'
servers:
  - url: http://apim-custom-onibxl.azure-api.net/publisher
paths:
  /ping:
    get:
      summary: GET
      operationId: get
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]