openapi: 3.0.1
info:
  title: Mock Response
  description: ''
  version: '1.0'
servers:
  - url: http://apim-custom-oni.azure-api.net/mock
paths:
  /get:
    get:
      summary: get
      operationId: get
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]