apiVersion: v1
kind: Namespace
metadata:
  name: viewer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: viewer-sa
  namespace: viewer
  annotations:
    azure.workload.identity/client-id: UMI_CLIENT_ID
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: viewer-config
  namespace: viewer
data:
  STORAGE_ACCOUNT_NAME: "storappsdevasd213"
  TABLE_NAME: "emails"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: viewer
  namespace: viewer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: viewer
  template:
    metadata:
      labels:
        app: viewer
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: viewer-sa
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: viewer
          image: IMAGE_NAME
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: viewer-config

---
apiVersion: v1
kind: Service
metadata:
  name: viewer
  namespace: viewer
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    app: viewer
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: viewer
