apiVersion: v1
kind: Namespace
metadata:
  name: inspector
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inspector-sa
  namespace: inspector
  annotations:
    azure.workload.identity/client-id: UMI_CLIENT_ID
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: inspector-config
  namespace: inspector
data:
  AZURE_KEYVAULT_NAME: "z-kv-apps-vd-dev"
  AZURE_OPENAI_DEPLOYMENT: "gpt-35-turbo"
  AZURE_OPENAI_API_VERSION: "2024-05-01-preview"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inspector
  namespace: inspector
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inspector
  template:
    metadata:
      labels:
        app: inspector
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: inspector-sa
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: inspector
          image: IMAGE_NAME
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: inspector-config

---
apiVersion: v1
kind: Service
metadata:
  name: inspector
  namespace: inspector
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    app: inspector
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: inspector
