trigger:
  branches:
    include:
      - main
  paths:
    include:
      - ui-chat/**

pool:
  name: Default

variables:
  - group: SEC_MS
  - name: SWA_NAME
    value: "z-swa-apps-dev"
  - name: SWA_RESOURCE_GROUP
    value: "z-rg-apps-dev"
  - name: APP_LOCATION
    value: './'
  - name: OUTPUT_LOCATION
    value: 'build'

steps:

  - script: |
      npm install
      REACT_APP_API_URL="http://9.163.147.163/chat/v1/message" npm run build
    displayName: 'Build React App'
    workingDirectory: ui-chat

  - task: Bash@3
    displayName: "Azure Upload SWA"
    inputs:
      targetType: "inline"
      workingDirectory: ui-chat
      script: |
        echo "Uploading build output to SWA..."
        ls
        SWA_CLI_DEPLOYMENT_TOKEN=$TOKEN swa deploy ./build/
    env:
      TOKEN: $(SWATOKEN)