trigger:
  branches:
    include:
      - main
  paths:
    include:
      - ui-chat/**

pool:
  name: Default

variables:
  - group: SEC_MS
  - name: SWA_NAME
    value: "z-swa-apps-dev"
  - name: SWA_RESOURCE_GROUP
    value: "z-rg-apps-dev"
  - name: APP_LOCATION
    value: './'
  - name: OUTPUT_LOCATION
    value: 'build'

steps:
  # - task: NodeTool@0
  #   inputs:
  #     versionSpec: '18.x'
  #   displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'Build React App'
    workingDirectory: ui-chat

  - task: Bash@3
    displayName: "Azure login"
    inputs:
      targetType: "inline"
      workingDirectory: ui-chat
      script: |
        az login --service-principal \
          --username "$SP_USERNAME" \
          --password "$SP_PASSWORD" \
          --tenant "$TENANT_ID"
    env:
      SP_USERNAME: $(ARMCLIENTID)
      SP_PASSWORD: $(ARMCLIENTSECRET)
      TENANT_ID: $(ARMTENANTID)

  - task: Bash@3
    displayName: "Azure Upload SWA"
    inputs:
      targetType: "inline"
      workingDirectory: ui-chat
      script: |
        echo "Uploading build output to SWA..."
        az staticwebapp upload \
          --name $SWA_NAME \
          --resource-group $SWA_RESOURCE_GROUP \
          --source $OUTPUT_LOCATION \
          --output-location $OUTPUT_LOCATION