parameters:
- name: stages
  type: object
  default: []

stages:
- ${{ each stage in parameters.stages }}:
  - stage: '${{ stage.name }}'
    displayName: '${{ stage.name }} Deployment'
    variables:
      - group: SEC_MS
      - name: RESOURCE_GROUP_NAME
        value: 'z-rg-ingress-dev'

    jobs:
    - job: BuildAndPublish
      displayName: 'Build and Publish'
      pool:
        name: Default
      steps:

        - task: DownloadPipelineArtifact@2
          inputs:
            buildType: 'specific'
            project: '$(System.TeamProject)'
            pipeline: 'Build app receiver'
            runVersion: 'latest'
            artifact: 'receiver-artifacts'
            path: '$(Build.ArtifactStagingDirectory)/receiver-artifacts'

        - task: PowerShell@2
          displayName: Set publishing variables
          inputs:
            targetType: inline
            script: |
              Set-StrictMode -Version Latest
              $ErrorActionPreference = "Stop"
              $VerbosePreference = "Continue"
              $InformationPreference = "Continue"

              az login --service-principal --username "$env:SP_USERNAME" --password "$env:SP_PASSWORD" --tenant "$env:TENANT_ID"

              $azureAccessToken = az account get-access-token --query "accessToken" --output tsv
              Write-Host "##vso[task.setvariable issecret=true;variable=AZURE_BEARER_TOKEN]$azureAccessToken"
              Write-Host "##vso[task.setvariable issecret=true;variable=AZURE_CLIENT_ID]$env:SP_USERNAME"
              Write-Host "##vso[task.setvariable issecret=true;variable=AZURE_CLIENT_SECRET]$env:SP_PASSWORD"
              Write-Host "##vso[task.setvariable issecret=true;variable=AZURE_TENANT_ID]$env:TENANT_ID"
          env:
            SP_USERNAME: $(ARMCLIENTID)
            SP_PASSWORD: $(ARMCLIENTSECRET)
            TENANT_ID: $(ARMTENANTID)

        - task: PowerShell@2
          displayName: Get Aks Context and publish app
          inputs:
            targetType: "inline"
            workingDirectory: releases/receiver
            script: |
              $resourceGroup = "${{ stage.AKSRG }}"
              $clusterName = "${{ stage.AKS }}"

              az aks get-credentials --resource-group $resourceGroup --name $clusterName --overwrite-existing
              $umiId = az identity show --name "umi-receiver" --resource-group "z-rg-apps-dev" --query clientId -o tsv

              $imagePath = "$(Build.ArtifactStagingDirectory)/receiver-artifacts/image"
              $image = Get-Content -Path $imagePath -Raw
              $image = $image.Trim()
              $version = "1.0.001"

              helm upgrade --install receiver ./HELM `
                -f ./HELM/values.yaml `
                --set appVersion="$version" `
                --set image="$image" `
                --set umiClientId="$umiId"