trigger: none

pool:
  name: Default

parameters:
  - name: dev
    displayName: DEV
    type: boolean
    default: true

stages:
  - template: pipeline-template.yaml
    parameters:
      stages:
        - ${{ if eq(parameters.dev, true) }}:
            - name: "Deploy_to_Apim_v2_Dev"
              environmentCode: dev
              AKS: "akscluster"
              AKSRG: "z-rg-aks-dev"
              subscriptionId: "42cc25b1-5f27-40a1-a857-9668d4e6e278"