trigger: none

pool:
  name: Default

parameters:
  - name: dev
    displayName: DEV
    type: boolean
    default: true

stages:
  - template: pipeline-template.yaml
    parameters:
      stages:
        - ${{ if eq(parameters.dev, true) }}:
            - name: "Deploy_to_Apim_v2_Dev"
              environmentCode: dev
              ENVIRONMENT: DEV
              AKS: "akscluster"
              AKSRG: "z-rg-aks-dev"
              subscriptionId: "315e574e-7153-4853-8cfe-fa416bb08a23"