apis:
  - name: business-external-authentication
    properties:
      apiRevision: 1
      serviceUrl: "https://login.microsoftonline.com/16850073-4977-4869-9163-08e8d38eac81/oauth2"
    diagnostics:
      - name: applicationinsights
        properties:
          loggerId: "/subscriptions/29d54a7c-6344-43b6-a628-0b0800596188/resourceGroups/we-ir-rg-apicatalog-prd/providers/Microsoft.ApiManagement/service/we-ir-apim-apicatalog-prd/loggers/we-ir-logger-apicatalog-prd" 
          